[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
smallvec = "1.10.0"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false
path = "src/bench.rs"
